### ISSUE TITLE
32bpp instead of the original 24bpp

### ISSUE THREAD

**Issue by Lebedev30** [crskycode/CIRCUS_CRX_Tool#1]
Can someone explain to me how I can't create crx files in 24bpp using CIRCUS_CRX_Tool?
What settings do I need to specify?

I have tried dozens of options of settings in json file, it creates only 32bpp crx file.
And VN De capo cannot display it on the screen, except for colored bars....

**Comment by crskycode** [comment]
Convert your PNG file to 24bpp format and then it will work.
I've improved the png export logic in `v1.1`, it will now automatically export 24bpp CRX file as 24bpp PNG file.

**Comment by Lebedev30** [comment]
> Convert your PNG file to 24bpp format and then it will work. I've improved the png export logic in `v1.1`, it will now automatically export 24bpp CRX file as 24bpp PNG file.

It's all working now, checked.
